#include "COLORCODER.h"

int main() {
    COLORCODER::testNumberToPair(4, COLORCODER::WHITE, COLORCODER::BROWN);
    COLORCODER::testNumberToPair(5, COLORCODER::WHITE, COLORCODER::SLATE);

    COLORCODER::testPairToNumber(COLORCODER::BLACK, COLORCODER::ORANGE, 12);
    COLORCODER::testPairToNumber(COLORCODER::VIOLET, COLORCODER::SLATE, 25);

    COLORCODER::printColorCodingReference();

    return 0;
}
